### ISSUE TITLE
QR code not working

### ISSUE THREAD

**Issue by Guray00** [pranavms13/whatsapp-node-api#11]
I don't know if i'm doing something wrong, but after asking for the qr code, i get the response and i save it as html file. Then i open with a browser it correctly shows the qr code, but whatsapp gives a error asking to check if the qr code is from web.whatsapp.com (doesn't recognize it). What should i do? I'm using an italian whatsapp account.

**Comment by choyan** [comment]
Remove `session.json` and `last.qr` and try again.

**Comment by yoki128** [comment]
I have the same error. when trying to scan the qr it gives me an error "the code could not be scanned. Make sure you have web.whatsapp.com open and scan the code again"

**Comment by llermaly** [comment]
I  have the same problem and tried to print the code in the console. On this case the account links but the library throws error : 

![image](https://user-images.githubusercontent.com/8575569/122777155-c3a24700-d279-11eb-95db-40184a869706.png)

p.s : using whatsapp-web.js directly works without problem

**Comment by llermaly** [comment]
solved updating whatsapp-web to the last version

**Comment by yoki128** [comment]
> I have the same problem and tried to print the code in the console. On this case the account links but the library throws error :
> 
> ![image](https://user-images.githubusercontent.com/8575569/122777155-c3a24700-d279-11eb-95db-40184a869706.png)
> 
> p.s : using whatsapp-web.js directly works without problem

how do you use whatsapp-web.js directly

**Comment by llermaly** [comment]
> > I have the same problem and tried to print the code in the console. On this case the account links but the library throws error :
> > ![image](https://user-images.githubusercontent.com/8575569/122777155-c3a24700-d279-11eb-95db-40184a869706.png)
> > p.s : using whatsapp-web.js directly works without problem
> 
> how do you use whatsapp-web.js directly

```
const { Client } = require('whatsapp-web.js');
const client = new Client();

client.on('qr', (qr) => {
    // Generate and scan this code with your phone
    console.log('QR RECEIVED', qr);
});

client.on('ready', () => {
    console.log('Client is ready!');
});

client.on('message', msg => {
    if (msg.body == '!ping') {
        msg.reply('pong');
    }
});

client.initialize();
```
