### ISSUE TITLE
Can't send Messages

### ISSUE THREAD

**Issue by ismaelivan** [pranavms13/whatsapp-node-api#13]
Hello, good day!, 

Thanks by share your api

i try test your api with postman, but i recived this error

![dd](https://user-images.githubusercontent.com/66751369/98588441-52d19000-2291-11eb-93c6-2222a542c96d.PNG)

How pass the params?

With the get methods i havent problem

![dd2](https://user-images.githubusercontent.com/66751369/98588702-be1b6200-2291-11eb-952d-343b60039d58.PNG)

Thanks in advance

**Comment by pranavms13** [comment]
the request body is wrong.
you are sending ``[{"message":"test"}]`` which is an array

the body accepts only a single object with a message key
try sending ``{"message":"test"}``
