### ISSUE TITLE
Error on Post Request

### ISSUE THREAD

**Issue by PetrosM263** [pranavms13/whatsapp-node-api#19]
When i use post requst to send messages i get a success message but my whatsapp app is not showing any response or something to show that i sent a message and it got 1 tick, 2 tick or received. Below i attached my screenshot code and output screenshot as well as an output file. If you can help please do because i dont know where i am going wrong.

![Screenshot (40)](https://user-images.githubusercontent.com/56104773/103071495-5d8b7e80-45cc-11eb-9957-d100ffad125b.png)
![Screenshot (42)](https://user-images.githubusercontent.com/56104773/103071500-5f554200-45cc-11eb-80a3-575205dbfe12.png)
[sendChatResponse.txt](https://github.com/pranavms13/whatsapp-node-api/files/5738659/sendChatResponse.txt)

**Comment by pranavms13** [comment]
Do not use the angular brackets in the URL
Try `` http://localhost:5000/chat/sendmessage/263778566457 ``
instead of ~~`` http://localhost:5000/chat/sendmessage/<263778566457> ``~~
