### ISSUE TITLE
Send images

### ISSUE THREAD

**Issue by Deco-code** [pranavms13/whatsapp-node-api#2]
has how to send the image by url? Not encoding in base64

**Comment by pranavms13** [comment]
Feature Added !! 
https://github.com/pranavms13/whatsapp-node-api/commit/207decf94e3e8c444aa6b8f0248fd70b633c796d

**Comment by pranavms13** [comment]
Look into https://github.com/pranavms13/whatsapp-node-api/blob/master/APIDOC.MD for usage
