### ISSUE TITLE
Call-to-Action please add features

### ISSUE THREAD

**Issue by RianEka** [pranavms13/whatsapp-node-api#24]
please add features
![2-1](https://user-images.githubusercontent.com/68814381/109121915-735b2280-777a-11eb-9f3e-aaeec61280c8.png)

**Comment by esteves67** [comment]
@RianEka That feature can't be added since its only available in the official whatsapp business api, normal users don't have access to it, just big companies.

**Comment by pranavms13** [comment]
it is available on Official WhatsApp business API's
Cannot be added here sorry.
