### ISSUE TITLE
post image does not work properly.

### ISSUE THREAD

**Issue by RianEka** [pranavms13/whatsapp-node-api#4]
post image does not work properly.
status post says success. however the image was not sent at the destination number.
curl -X POST http://142.11.xx.xx:5000/chat/sendimage/6282298749xxx -d "image=https://xxxxx.xxx/Content/img/version-12/icon/Icon-1.png&caption=test.jpeg"       

output :                     {"status":"success","message":"MediaMessage successfully sent"}

I looked on the temp folder server. The picture has been downloaded. but sending picture messages to the client. no process occurred / did not send a picture. please help.

**Comment by pranavms13** [comment]
it seems to work fine. I need more details on the problem
![image](https://user-images.githubusercontent.com/52594065/88830479-9ffe8a00-d1eb-11ea-94ef-977cfa109d58.png)
this will work

**Comment by RianEka** [comment]
right sir function. however the image is not correctly sent to the number in which the recipient is intended to receive the image.

**Comment by pranavms13** [comment]
please send logs

**Comment by RianEka** [comment]
sorry sir. there is no error logs for this case. it's just that the media is not really sent to the WhatsApp number that we are addressing. help me to check it sir. I really hope this send media really works

**Comment by RianEka** [comment]
@https://github.com/pranavms13/whatsapp-node-api/issues/4#issuecomment-665786327
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token i in JSON at position 1<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/home/vnc2/wabot4/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /home/vnc2/wabot4/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/home/vnc2/wabot4/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/home/vnc2/wabot4/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/vnc2/wabot4/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:203:15)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1145:12)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:63:19)</pre>
</body>
</html>

**Comment by pranavms13** [comment]
This isn't enough to understand the problem you are having. Please share the steps to reproduce the problem, and also the code snippet if you have edited anything.

**Comment by RianEka** [comment]
Sir. Send image error

POST : /chat/sendimage/6282298749468
(node:2126) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeE
rror: Cannot read property 'default' of undefined
    at Object.window.WWebJS.processMediaData (__puppeteer_evaluation_script__
:91:53)
    at Object.window.WWebJS.sendMessage (__puppeteer_evaluation_script__:22:4
6)
    at __puppeteer_evaluation_script__:9:45
    at ExecutionContext._evaluateInternal (/home/api/wabot/node_modules/puppe
teer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2126) UnhandledPromiseRejectionWarning: Unhandled promise rejection. Th
is error originated either by throwing inside of an async function without a
catch block, or by rejecting a promise which was not handled with .catch(). (
rejection id: 1)
(node:2126) [DEP0018] DeprecationWarning: Unhandled promise rejections are de
precated. In the future, promise rejections that are not handled will termina
te the Node.js process with a non-zero exit code.

please help.
