### ISSUE TITLE
About new Whatsapp Beta Update

### ISSUE THREAD

**Issue by mraydok** [pranavms13/whatsapp-node-api#42]
Hi sir,

Whatsapp publish a beta version. we try to scan qr code in this version but its not work. Will you update new whatsapp features ?

**Comment by monossido** [comment]
https://github.com/pedroslopez/whatsapp-web.js has a branch for that, but is in development and I can't go further than viewing the qr code (and often it does not appear)

**Comment by monossido** [comment]
Actually the "multidevice" branch from the orginal library https://github.com/pedroslopez/whatsapp-web.js it's working for me with Whatsapp beta.
Using whatsapp-node-api installing whatsapp-web.js#multidevice it's not working.

Any comments from the author?

**Comment by monossido** [comment]
I have implemented some simple fixes in order get it working with multidevice whatsapp beta
My repo -> https://github.com/monossido/whatsapp-node-api/
PR -> https://github.com/pranavms13/whatsapp-node-api/pull/45

**Comment by nanoeray** [comment]
@monossido your repo not working.

**Comment by monossido** [comment]
@nanoeray I'm using it in "production" for an automation.
If you tell me the problem maybe I can help

**Comment by nanoeray** [comment]
I’ve solved the problem updating whatsapp-web.js to latest 1.15.1 thanks

**Comment by monossido** [comment]
whatsapp-web.js is updated to 1.16.1 supporting logacy whatsapp and "beta" whatsapp
Here it is the PR for that https://github.com/pranavms13/whatsapp-node-api/pull/60

**Comment by pranavms13** [comment]
Working fine now. Thanks to @monossido
