### ISSUE TITLE
Error After Scanning QR in updated WhatsApp

### ISSUE THREAD

**Issue by ishrarg** [pranavms13/whatsapp-node-api#49]
I have successfully implemented in more than 25 (Windows10 ) machines till now. For a couple of days (maybe 10 days), on random few NEW computers gives this message after scanning QR Code.
@pranavms13  Please help soon.

(node:10680) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:35:78
    at ExecutionContext._evaluateInternal (C:\xyz\nm\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\xyz\nm\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\xyz\nm\node_modules\whatsapp-web.js\src\Client.js:161:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nanoeray** [comment]
update whatsapp-web.js to the latest version
